### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by yadianluffy** [Code-X-Mania/Filestreambot-pro#3]
Please could you change the download link that the bot generates from the http protocol to https as it tends to give an error in some modern browsers
![Captura de pantalla (6)](https://user-images.githubusercontent.com/88897873/146305899-9fbc108c-ca33-4f8c-b1ad-492a6efc49ed.png)

**Comment by Code-X-Mania** [comment]
just edit some codes by default it is http becuase not all servers have ssl
