### ISSUE TITLE
Violates the tos of heroku and railway

### ISSUE THREAD

**Issue by sandip01004** [Code-X-Mania/Filestreambot-pro#5]
<details>
<summary> <h3 style="colour:hsl(0, 100%, 50%);">this repository cannot be deployed </h3></summary>
<p> The bot violates the terms of service of railway and heroku. </p>
</details>

**Comment by Code-X-Mania** [comment]
can be deployed just fork to deploy on heroku

**Comment by Code-X-Mania** [comment]
for railway dont use the deploy button just fork and connect repo
