### ISSUE TITLE
#Request

### ISSUE THREAD

**Issue by rubandurai27** [Code-X-Mania/Filestreambot-pro#6]
![Screenshot_2022-01-25-12-26-21-859_com android chrome](https://user-images.githubusercontent.com/77948100/150927197-7379c150-c937-4b33-9c56-2d30fbfdacdc.jpg)

Change stream site interface like this with ads .

**Comment by Code-X-Mania** [comment]
i dont know how to!

**Comment by Code-X-Mania** [comment]
**_Also I am working on ads part stay tuned_**

**Comment by rubandurai27** [comment]
👍

**Comment by Code-X-Mania** [comment]
do u have code?

**Comment by rubandurai27** [comment]
https://gist.github.com/rubandurai27/c2c3c17f11caa3b2c21cfbad927abbfe

**Comment by Code-X-Mania** [comment]
will check!

**Comment by Code-X-Mania** [comment]
bro show me the live version!

**Comment by Code-X-Mania** [comment]
i suspect this code has issues

**Comment by rubandurai27** [comment]
![Screenshot_2022-01-29-18-54-03-883_com android chrome](https://user-images.githubusercontent.com/77948100/151662817-a56532f5-233f-4789-83bf-44ee494f918a.jpg)

**Comment by rubandurai27** [comment]
![Screenshot_2022-01-31-09-48-04-633_com rhmsoft edit](https://user-images.githubusercontent.com/77948100/151738424-93e3181e-ca1a-466d-89a0-16411765d707.jpg)

Plz add this code in main repo ..

**Comment by Code-X-Mania** [comment]
will add later! busy for now!!

**Comment by rubandurai27** [comment]
> do u have code?

https://justpaste.it/1wl3u

Change something .
