### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rubandurai27** [Code-X-Mania/Filestreambot-pro#7]
![Screenshot_2022-01-26-09-29-28-322_org telegram plus](https://user-images.githubusercontent.com/77948100/151102334-50be1a8c-dba7-4066-a775-3b9f544a2dcc.jpg)

Change Download link & Stream link like http://{App_Name}.herokuapp.com/download/29/Maraikkayar_Arabikkadalin_Singam_2021_Tamil_HQ_HDRip_700MB_x264.mkv

**Comment by Code-X-Mania** [comment]
will be added soon this is part of the upcoming update

**Comment by rubandurai27** [comment]
Please Update The Feature 🙏

**Comment by adarsh-goel** [comment]
ok explain about it in @agprojectschat
